/*
    Colección Canciones
                        */


db.canciones.insertMany([

    {
        id: 1,
        cancion: "What's Going On", 
        artista: "Marvin Gaye",
        genero_cancion: ["R&B", "Soul"],
        num_reproducciones: 200000,
        porcentaje_visita: 0.1

    },

    { id: 1, cancion: "What's Happening Brother", artista: "Marvin Gaye", genero_cancion: ["R&B", "Soul"], num_reproducciones: 150000, porcentaje_visita: 0.4 },
    { id: 1, cancion: "Flyin' High (in the Friendly Sky)", artista: "Marvin Gaye", genero_cancion: ["R&B", "Soul"], num_reproducciones: 100000, porcentaje_visita: 0.1 },
    { id: 1, cancion: "Save the Children", artista: "Marvin Gaye", genero_cancion: ["R&B", "Soul"], num_reproducciones: 100000, porcentaje_visita: 0.1 },
    { id: 1, cancion: "God Is Love", artista: "Marvin Gaye", genero_cancion: ["R&B", "Soul"], num_reproducciones: 100000 , porcentaje_visita: 0.1},
    { id: 1, cancion: "Mercy Mercy Me (The Ecology)", artista: "Marvin Gaye", genero_cancion: ["R&B", "Soul"], num_reproducciones: 150000, porcentaje_visita: 0.2 },
    { id: 1, cancion: "Right On", artista: "Marvin Gaye", genero_cancion: ["R&B", "Soul"], num_reproducciones: 70000, porcentaje_visita: 0.1 },
    { id: 1, cancion: "Wholy Holy", artista: "Marvin Gaye", genero_cancion: ["R&B", "Soul"], num_reproducciones: 120000, porcentaje_visita: 0.1 },
    { id: 1, cancion: "Inner City Blues (Makes Me Wanna Holler)", artista: "Marvin Gaye", genero_cancion: ["R&B", "Soul"], num_reproducciones: 200000, porcentaje_visita: 0.15 },
    { id: 2, cancion: "Come Together", artista: "The Beatles", genero_cancion: ["Blues rock", "Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 3000000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Something", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 2000000, porcentaje_visita: 0.12 },
    { id: 2, cancion: "Maxwell's Silver Hammer", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 500000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Oh! Darling (Remastered 2009)", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 450000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Octopus's Garden", artista: "The Beatles", genero_cancion: ["Pop", "Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 700000, porcentaje_visita: 0.17 },
    { id: 2, cancion: "I Want You (She's So Heavy)", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 300000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Here Comes the Sun", artista: "The Beatles", genero_cancion: ["Pop Rock", "Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Because", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "You Never Give Me Your Money", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 500000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Sun King", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 700000, porcentaje_visita: 0.25 },
    { id: 2, cancion: "Mean Mr Mustard", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 500000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Polythene Pam", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 400000, porcentaje_visita: 0.5 },
    { id: 2, cancion: "She Came In Through The Bathroom Window", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 600000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Golden Slumbers", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Carry That Weight", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 1200000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "The End", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 2, cancion: "Her Majesty", artista: "The Beatles", genero_cancion: ["Música alternativa/Indie", "Folk", "Japanese Rock", "Rock", "J-Pop"], num_reproducciones: 2000000, porcentaje_visita: 0.05 },
    { id: 3, cancion: "Sir Duke", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Isn't She Lovely", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul"], num_reproducciones: 300000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Pastime Paradise", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul"], num_reproducciones: 200000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Knocks Me Off My Feet", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 70000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Another Star", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul"], num_reproducciones: 500000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Ordinary Pain", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 100000, porcentaje_visita: 0.3 },
    { id: 3, cancion: "Village Ghetto Land", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 300000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Summer Soft", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 500000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Love's In Need Of Love Today", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 2000000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Easy Goin' Evening (My Mama's Call)", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 300000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Ebony Eyes", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 400000, porcentaje_visita: 0.2 },
    { id: 3, cancion: "All Day Sucker", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 600000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Saturn", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 500000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "As", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 400000, porcentaje_visita: 0.3 },
    { id: 3, cancion: "Black Man", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 3, cancion: "Ngiculela - Es una Historia - I'm Singing", artista: "Stevie Wonder", genero_cancion: ["R&B", "Soul", "Música infantil", "Blues"], num_reproducciones: 100000, porcentaje_visita: 0.1 },
    { id: 4, cancion: "Smells Like Teen Spirit", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 3000000, porcentaje_visita: 0.5 },
    { id: 4, cancion: "In Bloom", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 2000000, porcentaje_visita: 0.1 },
    { id: 4, cancion: "Come As You Are", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 500000, porcentaje_visita: 0.4 },
    { id: 4, cancion: "Breed", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie", "Heavy metal", "Pop", "Rock"], num_reproducciones: 700000, porcentaje_visita: 0.07 },
    { id: 4, cancion: "Lithium", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 300000, porcentaje_visita: 0.1 },
    { id: 4, cancion: "Polly", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 400000, porcentaje_visita: 0.1 },
    { id: 4, cancion: "Territorial Pissings", artista: "Nirvana", genero_cancion: ["Grunge", "Música alternativa", "Indie", "Heavy metal", "Pop", "Rock"], num_reproducciones: 700000, porcentaje_visita: 0.1 },
    { id: 4, cancion: "Drain You", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie", "Heavy metal", "Pop", "Rock"], num_reproducciones: 800000, porcentaje_visita: 0.1 },
    { id: 4, cancion: "Lounge Act", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie", "Heavy metal", "Pop", "Rock"], num_reproducciones: 500000, porcentaje_visita: 0.06 },
    { id: 4, cancion: "Stay Away", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie", "Heavy metal", "Pop", "Rock"], num_reproducciones: 400000, porcentaje_visita: 0.1 },
    { id: 4, cancion: "On a Plain", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie", "Heavy metal", "Pop", "Rock"], num_reproducciones: 600000, porcentaje_visita: 0.33 },
    { id: 4, cancion: "Something In The Way", artista: "Nirvana", genero_cancion: ["Música alternativa", "Indie", "Heavy metal", "Pop", "Rock"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 5, cancion: "Creep", artista: "Radiohead", genero_cancion: ["Rock alternativo", "Pop"], num_reproducciones: 15000000, porcentaje_visita: 0.1 },
    { id: 6, cancion: "Wouldn't It Be Nice", artista: "The Beach Boys", genero_cancion: ["Pop barroco", "Sunshine pop"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 6, cancion: "Don't Talk (Put Your Head On My Shoulder)", artista: "The Beach Boys", genero_cancion: ["Pop barroco"], num_reproducciones: 300000, porcentaje_visita: 0.1 },
    { id: 6, cancion: "God Only Knows", artista: "The Beach Boys", genero_cancion: ["Pop barroco", "Sunshine pop"], num_reproducciones: 500000, porcentaje_visita: 0.1 },
    { id: 6, cancion: "I Know There's An Answer", artista: "The Beach Boys", genero_cancion: ["Pop barroco", "Pop psicodélico", "Pop progresivo"], num_reproducciones: 200000, porcentaje_visita: 0.1 },
    { id: 7, cancion: "Bigger Stronger", artista: "Coldplay", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 1000000, porcentaje_visita: 0.1},
    { id: 7, cancion: "Don't Panic", artista: "Coldplay", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 2000000, porcentaje_visita: 0.12 },
    { id: 7, cancion: "See You Soon", artista: "Coldplay", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 500000, porcentaje_visita: 0.1 },
    { id: 7, cancion: "High Speed", artista: "Coldplay", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 700000, porcentaje_visita: 0.1 },
    { id: 7, cancion: "Such A Rush", artista: "Coldplay", genero_cancion: ["Música alternativa", "Indie"], num_reproducciones: 3000000, porcentaje_visita: 0.1 },
    { id: 8, cancion: "Rocks Off", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 4000000, porcentaje_visita: 0.15 },
    { id: 8, cancion: "Rip This Joint", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 8, cancion: "Shake Your Hips", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 8, cancion: "Casino Boogie", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 500000, porcentaje_visita: 0.12 },
    { id: 8, cancion: "Tumbling Dice", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 8, cancion: "Sweet Virginia", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 3000000, porcentaje_visita: 0.1 },
    { id: 8, cancion: "Tom & Frayed", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 600000, porcentaje_visita: 0.21 },
    { id: 8, cancion: "Sweet Black Angel", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 500000, porcentaje_visita: 0.1 },
    { id: 8, cancion: "Loving Cup", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 8, cancion: "Happy", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 5000000, porcentaje_visita: 0.1 },
    { id: 8, cancion: "Turd On The Run", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 500000, porcentaje_visita: 0.4 },
    { id: 8, cancion: "Ventilator Blues", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 400000, porcentaje_visita: 0.1 },
    { id: 8, cancion: "I Just Want to See His Face", artista: "The Rolling Stones", genero_cancion: ["Country", "Música alternativa", "Indie", "Música infantil", "Folk", "Rock", "Blues"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 9, cancion: "Respect", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 3000000, porcentaje_visita: 0.1 },
    { id: 9, cancion: "Drown in My Own Tears", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 1000000, porcentaje_visita: 0.3 },
    { id: 9, cancion: "I Never Loved A Man (The Way I Love You)", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 2000000, porcentaje_visita: 0.1 },
    { id: 9, cancion: "Soul Serenade", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 9, cancion: "Don't Let Me Lose This Dream", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 800000, porcentaje_visita: 0.1 },
    { id: 9, cancion: "Baby, Baby, Baby", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 500000, porcentaje_visita: 0.33 },
    { id: 9, cancion: "Dr. Feelgood", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 600000, porcentaje_visita: 0.1 },
    { id: 9, cancion: "Good Times", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 800000, porcentaje_visita: 0.1 },
    { id: 9, cancion: "Do Right Woman, Do Right Man", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 1000000, porcentaje_visita: 0.1 },
    { id: 9, cancion: "Save Me", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 500000, porcentaje_visita: 0.2 },
    { id: 9, cancion: "A Change Is Gonna Come", artista: "Aretha Franklin", genero_cancion: ["R&B", "Soul"], num_reproducciones: 200000, porcentaje_visita: 0.1 },
    { id: 10, cancion: "See Emily Play", artista: "Pink Floyd", genero_cancion: ["Rock psicodélico"], num_reproducciones: 5000000, porcentaje_visita: 0.1 }

])